### ISSUE TITLE
pg255 Table 5-2 General Skill Feats (Dubious Knowledge)

### ISSUE THREAD

**Issue by Anguish1** [VestOfHolding/Pathfinder2EMistakes#2]
The Prerequisites for Dubious Knowledge on the table says "Trained in Recall Knowledge skill".  This should read "Trained in Recall Knowledge action" as there is no such skill.  The Automatic Knowledge feat on the same table illustrates the correct usage.

**Comment by lordcirth** [comment]
No, I think it's correct. In order to gain Dubious Knowledge in a skill, it has to be a skill you can Recall Knowledge with, and you must be trained in it.  Eg, in order to gain Dubious Knowledge in Arcana, you must be trained in Arcana. There is no such thing as being Trained in Recall Knowledge.

**Comment by VestOfHolding** [comment]
I'm gonna have to think on this, Anguish. I notice this is similar to the issue you brought up in the forums, where the book was referencing skill feats that are related to the Intimidation skill.

One of the things I was looking for in the forums for some of these more ambiguous ones was whether or not I saw other members of the community fairly quickly come back with an answer, and if there was a lot of agreement with that answer (such as post favorites).

In this case, I'm seeing exactly that in response to both of your issues, so I'm not sure how widespread the misunderstanding really is.

**Comment by Anguish1** [comment]
I'll be honest; I'm getting a sense of defensiveness on a bunch of these.  An attitude of "I figured it out" being some sort of appropriate response to the issues.  In this case specifically, I've given an example of how it's supposed to be, a couple lines further down the table.  If my issue is false, then the example I've given is the item that needs correction.

If the only thing this project does is correct character omissions and transpositions then... fine.  But I'm of the opinion that consistency in choice of words and methods of reference are typos.  That opinion appears not to align with the average contributor.  So be it.

**Comment by lordcirth** [comment]
Since you were confused by it, that implies it does need rewording.

**Comment by VestOfHolding** [comment]
I really don't mean to put on any sort of defensiveness, just being cautious about scope creep, and trying to figure out as best as I can if it's just one or two people that are confused about a certain piece of text, or a noticeably large chunk of people. Especially in a case like this where I understood it, so I'm trying to listen to the community to figure out if I'm in the minority or not in what limited ways I have.

**Comment by VestOfHolding** [comment]
Closing the issue as it has been added to the page. Thanks for the discussion.
